// reviewsData.js

export const CustomerReviewsList = [
    { name: "Amit Sharma", rating: 5, review: "Fantastic service, will definitely recommend to friends!" },
    { name: "Priya Reddy", rating: 4, review: "Good experience, but room for some improvement." },
    { name: "Rajesh Kumar", rating: 5, review: "Amazing experience, everything was perfect!" },
    { name: "Anjali Verma", rating: 3, review: "It was average, could have been better." },
    { name: "Suresh Patel", rating: 4, review: "Satisfied with the service, would use it again." },
    { name: "Vikram Singh", rating: 5, review: "Highly recommended! Will definitely come back." },
    { name: "Neha Gupta", rating: 4, review: "Good service, but there is room for improvement." },
    { name: "Manoj Yadav", rating: 5, review: "Excellent, I am very happy with the service!" },
    { name: "Ravi Mehra", rating: 3, review: "It was okay, but some areas can be improved." },
    { name: "Preeti Mishra", rating: 5, review: "Amazing service! Highly professional." },
    { name: "Karan Joshi", rating: 4, review: "Service was good, but needs a few tweaks." },
    { name: "Ritu Sharma", rating: 5, review: "Loved it! Will definitely recommend." },
    { name: "Harshika Rai", rating: 4, review: "Very good service, could improve delivery speed." },
    { name: "Ankit Jain", rating: 3, review: "Decent service, but can be faster." },
    { name: "Arvind Kumar", rating: 5, review: "Everything was perfect. Would love to use again." },
    { name: "Shalini Agarwal", rating: 4, review: "Great experience, would use again." },
    { name: "Nikhil Kapoor", rating: 5, review: "Top-notch service, highly recommend!" },
    { name: "Meera Singh", rating: 4, review: "Good service, satisfied overall." },
    { name: "Ramesh Chandra", rating: 5, review: "The best experience I've had. Totally worth it." },
    { name: "Simran Sethi", rating: 4, review: "Satisfactory service, but could be quicker." },
    { name: "Vishal Gupta", rating: 3, review: "Average experience, needs improvement." },
    { name: "Neeraj Kumar", rating: 5, review: "Absolutely wonderful, will use again." },
    { name: "Sonia Yadav", rating: 4, review: "Pretty good service, would recommend." },
    { name: "Tarun Sharma", rating: 5, review: "Outstanding service, beyond expectations." },
    { name: "Ishita Malhotra", rating: 3, review: "Okay experience, but they can improve." },
    { name: "Rupesh Singh", rating: 4, review: "Good service, would come back again." },
    { name: "Nisha Mehta", rating: 5, review: "Great experience, loved it!" },
    { name: "Pradeep Kumar", rating: 4, review: "Very good service, but delivery took some time." },
    { name: "Pooja Mishra", rating: 5, review: "Perfect service, couldn't be happier." },
    { name: "Tanuja Yadav", rating: 4, review: "Good, but room for improvement." },
    { name: "Ankur Jain", rating: 5, review: "Exceeded my expectations, amazing service!" },
    { name: "Shivani Kapoor", rating: 4, review: "Pretty good, just a little slow." },
    { name: "Rahul Joshi", rating: 3, review: "The service was okay, nothing special." },
    { name: "Geeta Verma", rating: 5, review: "Top service! Would definitely recommend." },
    { name: "Vinod Kumar", rating: 4, review: "Good service, needs a little more polish." },
    { name: "Ritu Kapoor", rating: 5, review: "Amazing, would recommend to everyone!" },
    { name: "Ajay Sharma", rating: 4, review: "Service was good, would come back again." },
    { name: "Meenakshi Jain", rating: 5, review: "Perfect experience, very satisfied!" },
    { name: "Gaurav Gupta", rating: 4, review: "Good experience, though some aspects could be improved." },
    { name: "Kavita Yadav", rating: 5, review: "Excellent service, would definitely recommend." },
    { name: "Sudhir Kumar", rating: 3, review: "It was average, could be faster." },
    { name: "Neelam Sethi", rating: 4, review: "Nice service, happy overall." },
    { name: "Alok Mehra", rating: 5, review: "Couldn't ask for better service, amazing!" },
    { name: "Vinita Rai", rating: 4, review: "Good service, but still has room to improve." },
    { name: "Kiran Verma", rating: 5, review: "Exceptional service, highly recommend." },
    { name: "Sandeep Kumar", rating: 4, review: "Overall good, but needs to improve the response time." },
    { name: "Shubhi Sharma", rating: 3, review: "Not bad, but could use some improvements." },
    { name: "Deepak Yadav", rating: 5, review: "Absolutely satisfied with the service." },
    { name: "Nishant Jain", rating: 4, review: "Very good service, but needs to improve efficiency." },
    { name: "Priya Joshi", rating: 5, review: "Totally worth it, great experience!" },
    { name: "Amit Joshi", rating: 4, review: "Good service, would use it again." },
    { name: "Ravina Singh", rating: 5, review: "Loved it! Great service." },
    { name: "Pankaj Mehra", rating: 4, review: "Good experience, but some minor improvements needed." },
    { name: "Divya Gupta", rating: 5, review: "Excellent! Totally satisfied." },
    { name: "Gaurav Sharma", rating: 4, review: "Satisfactory, could be better in some areas." },
    { name: "Swati Agarwal", rating: 5, review: "Amazing service, will definitely recommend!" }
];

export default CustomerReviewsList;
